version: '3'

services: 
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        expose:
            - '80'
        ports:
            - '80:80'
        volumes:
            - /app/node_modules
            - ./frontend:/app
